// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Miki.Bot.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Miki.Migrations
{
    [DbContext(typeof(MikiDbContext))]
    [Migration("20190804104840_Configuration")]
    partial class Configuration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Miki.Config", b =>
            {
                b.Property<string>("Token");
                
                b.Property<string>("SharpRavenKey");

                b.Property<string>("DatadogHost");

                b.Property<string>("RedisConnectionString");

                b.Property<string>("MikiApiBaseUrl");

                b.Property<string>("MikiApiKey");

                b.Property<string>("ImageApiUrl");

                b.Property<string>("CdnRegionEndpoint");

                b.Property<string>("CdnAccessKey");

                b.Property<string>("CdnSecretKey");

                b.Property<string>("RabbitUrl");

                b.Property<string>("DanbooruCredentials");

                b.Property<string>("BunnyCdnKey");

                b.ToTable("Configuration");
            });
#pragma warning restore 612, 618
        }
    }
}
